- parser.go
- worksheets.go
- worksheets_test.go
Fixes issue #5. A couple of opinions encoded here:
* Defining more than one worksheet with the same name is a fatal error
* Attempting to parse a file which contains zero worksheet defs is a fatal error
I can see reasons for/against the second, so I'm happy to discuss if you want.
Thanks!
> Allow multiple worksheet defs per file

- dbstore.go
- dbstore_test.go
Was playing around with this today and ran into issues saving worksheets sometimes, if I saved before setting all the fields, because the `RowsAffected` didn't match the `len(diff)`. Since the `"unable to update old values"` block wasn't tested, I guessed the behavior wasn't critical, and removing it fixes the issues I was having.
> db update for undefined fields

- .circleci/config.yml
Recently [1], satori/go.uuid changed the signature of various functions, including NewV4 used by sqlx runner. As a result, sqlx runner does not compile at HEAD anymore. A change was submitted to sqlx runner [2], but meanwhile, to keep our build green, we're forcibly setting the satory/go.uuid version to a specific sha. This approach is chosen over vendoring since the intent of worksheets is to be used as a library in a project which would itself manage vendoring.
[1] https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c
[2] https://github.com/mgutz/dat/pull/77
> Fixing with a temporary fix the go.uuid <> sqlx runner issues

- dbstore.go
- dbstore_test.go
- dbtestutil_test.go
- refs_test.go
- slices_test.go
- worksheets.go
Now that we are storing text values directly, we need to treat undefined as NULLs, otherwise when they are read back, we read them as the text "undefined". Plus, using NULLs to represent undefined values is kinda was RDBMS call for!
> Fixing handling of undefined

- dbstore.go
- parser.go
- parser_test.go
- tree.go
- types.go
- types_test.go
- values.go
- worksheets.go
- worksheets_test.go
- Making Definition a Type, and exporting it
- Doing type resolution to ensure ws.Type() returns the definition of this worksheet
- And this removes the need to have a tWorksheetType which was kinda ugly anyways, good riddance
> Exporting worksheets' definitions

- computed_by_test.go
- expressions.go
- features/some_expressions.ws
- parser.go
- parser_test.go
- tree.go
This is a stepping stone to introducing more statements such as `if`, `for`, `x := expr`, etc. When we do introduce them, we can model them as optionally value producing expressions, and add a `ReturnsValue() bool` func to interrogate whether they do or do not, and require the top-level expression of a `computed_by` to produce a value.
> Being go-ish and requiring explicit return

- dbstore.go
- parser.go
- parser_test.go
- slices_test.go
- tree.go
- types.go
- types_test.go
- values.go
- worksheets.go
- worksheets_test.go
Changed `Field` and `SliceType` to be exported, so we can figure out field types based on the definition (and know e.g. if we need to `Set` a value or `Append` it).
> Export more types

- dbstore.go
- dbstore_test.go
- expressions.go
By capturing the version at which sign-off is given, we can have a computed field automatically indicating whether a worksheet was signed-off or not.
To make this work, the update must set the new version and trigger downstream calculations -- whereas before we overlooked that and did a straight change in the internal data table. This also means that if a failure occurs, we must properly rollback the version change, and do so consistently on every exit point of the update function. To this end, using a deferred func to rollback, which gets turned off if-and-only-if we know the update will succeed.
> Capturing the 'signoff pattern' (and fixes to update to ensure it works)

- marshaling.go
- marshaling_test.go
- parser.go
Introducing a `StructScan` func to export worksheets to Golang structs. This is meant to simplify accessing worksheet data, when it is time for it -- the data -- to leave it's comfortable home of sheets.
Some details about how this works, and how it makes things simpler:
- You can define a struct with `ws:"field_name"` tag on its fields, and `StructScan` will export the worksheet fields matching into the Golang struct. For instance:
```var data struct {
Name   string  `ws:"full_name"`
Age    int     `ws:"age"`
Phone  *string `ws:"phone_number"`
}
```
- Since all fields in a worksheet are optional, pointer receivers are also supported. For instance, in the example above, we are indicating that `Name` and `Age` must be set for `StructScan` to succeed, whereas `Phone` is expected to be …
> Implementing StructScan

- dbutil.go
@lgonzalez-silen 's observation on `neatdb` `RunTransaction` while reviewing https://phabricator.helloeave.com/D986. Same code is here. If `fn` panics, rather than returning an error, currently, `Rollback ` won't be called.
> Defer autorollback before fn call in case fn panics

- computed_by_test.go
- constrained_by_test.go
- dbstore.go
- expressions.go
- expressions_test.go
- marshaling.go
- parser.go
- parser_test.go
- slices_test.go
- tree.go
- types.go
- types_test.go
- values.go
- values_test.go
- worksheets.go
- worksheets_test.go
This is a mostly working first cut of cross worksheet updates. One of the contrived example under test is
```
worksheet parent {
1:child_amount number[2] computed_by {
return child.amount
}
2:child child
}
worksheet child {
5:amount number[2]
}
```
**Implementation Notes**
- Expressions such as `foo` or `foo.bar` are now selectors, and we replace the `tVar` type by a `tSelector` type.
- Selectors can either be paths to select a specific field, as in the above example where `child.amount` points to the `amount` field of `child` worksheet, or selectors can be more complex as in `children.amount` where `children` is a `[]child` would be a `[]number[2]` essentially selecting a specific field on a slice level.
- Dependents handling is expanded to cross worksheet dependents. Minor change, …
> Cross worksheet updates, a start

- computed_by_test.go
- dbstore.go
- dbstore_test.go
- dbtestutil_test.go
- refs_test.go
- schema.sql
- slices_test.go
- worksheets.go
- worksheets_test.go
Consider the worksheets
```
worksheet parent {
1:child_amount number[2] computed_by { return child.amount }
2:child child
}
worksheet child {
5:amount number[2]
}
```
when a child is loaded, and its `amount` updated, this must properly flow to its parents. As a result, we must load those parents when loading the child so that updates can flow through properly.
To this end, we now track and persist parent pointers records in a newly introduced `worksheet_parents` table. This change is all about correctly saving and updating those records, as well as correctly loading parents when loading a worksheet.
> Cross Worksheet updates, across persistence boundaries

- computed_by_test.go
- dbstore_test.go
- dbtestutil_test.go
- refs_test.go
- slices_test.go
Calling it `snapshotDbState` and it returns a `dbState` struct.
> Instead of four returns from DbState, return struct

- clone.go
- clone_test.go
- slices_test.go
- values.go
- worksheets.go
Adding `Clone()` method on a worksheet. This does a deep-copy of the underlying worksheet, and all of its data structures.
(Fixing `doAppend` which was modifying `lastRank` of the slice being appended to, instead of only setting a new value in the new slice which contains the appended element.)
> Ability to clone a worksheet

- computed_by_test.go
- expressions.go
- values.go
- worksheets.go
We had the issue where the `sum` in the following worksheet
worksheet sum_example {
1:nums []number[0]
2:sum number[0] computed_by {
sum(nums)
}
}
would be `undefined` when initiliazed, and when the first number is appended to the `nums`, it would actually represent the sum of numbers.
However, we've seen in practice that we want the sum to be defined to `0` when initializing the worksheet, as this actually represents the initial state.
To achieve this, suggesting two changes:
1. Slice fields start empty (vs undefined). Currently, only appending and deleting from slices is allowed, and we're therefore already saying that slice fields are never undefined, rather empty. This change makes it concrete in the internals.
2. When creating a new instance of a worksheet, we trigger all …
> A solution for sums needing to be initialized at 0

- dbstore.go
- dbstore_test.go
Right now, removing a field from a worksheet definition causes issues if that field exists in the db. We should be allowed to deprecate fields, and therefore shouldn't return an error when a field exists in the db but not in our definition.
> Allow fields to be deprecated

- clone.go
- clone_test.go
- computed_by_test.go
- constrained_by_test.go
- dbstore.go
- dbstore_test.go
- marshaling_test.go
- refs_test.go
- values.go
- values_test.go
- worksheets.go
- worksheets_test.go
Went from 219 uses down to 11 uses.
Next up, rename `NewValue` to `ParseLiteral`!
> Cleanup: using NewNumberFromXxx vs the general NewValue

- testutil_test.go
- values.go
- values_test.go
Testing https://github.com/helloeave/worksheets/pull/115 I found that printing out worksheets with cycles was not working.
Open to suggestions for the format for refs already seen. Currently it prints out <ref_to_seen_worksheet>.
> Give ws stringer a way to break cycles.

- dbstore.go
- enums_test.go
Delegating to text type, since we're storing enum typed fields as text.
> Implement dbReadValue for enum types

- expressions.go
- runtime_test.go
- values.go
tl;dr see `rFoldNumbers` and then how this generic helper is used to write `min`, `max`, `sum`. Adding a `slice` func to create slices inline, which helps with testing.
Adding helper `slice` to create slices, and adding `min` and `max` which works over a wide range of numerical arguments: trying to allow any possible ways in which numbers could be passed, list of numbers, slices of numbers, slices of slices of numbers, a combination of all of the above. For that, introducing a way to 'fold' numerical arguments which is a just a way to iterate over all numerical arguments in a generic way.
Changing `sum` to be based over the same scaffolding which `min` and `max` are based on.
> Adding min and max (and slice)

- tools/wstest.go
- wstesting/wstesting.go
- wstesting/wstesting_test.go
Printing 'source:linenum:colnum: text: err' when errors are encountered.
> Nicer errors in wstesting

- expressions.go
- expressions_test.go
- parser.go
- parser_test.go
- runtime_test.go
- tree.go
Adding new function `avg`, which introduces some additional complexity: since an average can be calculated to a specific precision, and in the spirit of worksheets where precision and rounding must be explicitly provided, we need to have the ability to
1. Pass a rounding mode to a functional call (practically, attach a `tRound` to a `tCall`)
2. Allow the function implementation to decide whether a rounding mode is required or not
Doing this in a few steps:
- In the parser, explicitly looking for a parsing mode following a function call, and directly attaching this to the `tCall` node
- In the `compute` of `tCall`, implementing rounding to preserve the functionality we had before
- Extending `fnArgs` to also have a rounding mode, such that individual functions can choose to do something …
> Support for computing averages, with avg

- dbstore.go
- slices_test.go
When slices are modified, yet preserve their id and last rank, we do not need to update the value record, only the slice elements.
> Optimizing how slice references are recorded
