worksheets_test.go

Just standardizing some things; `grep`-ed around and found these.

Use require.True or require.False for bools

---

README.md
expressions.go
parser.go
worksheets.go
worksheets_test.go

Fixes #2 😀 
i'm sure there's lots to be cleaned up but some 👀  now would be much appreciated!

External computed by

---

parser.go
parser_test.go

Allow _ as separator in numbers

---

expressions.go
parser.go
parser_test.go

Support for boolean expressions.

---

README.md
dbstore.go
dbstore_test.go
dbtestutil_test.go
parser.go
parser_test.go
schema.sql
slices_test.go
testutil_test.go
types.go
values.go
worksheets.go
worksheets_test.go

Support for slices

---

dbstore.go
dbstore_test.go
parser.go
parser_test.go
refs_test.go
slices_test.go
testutil_test.go
types.go
types_test.go
values.go
worksheets.go
worksheets_test.go

Support for references to worksheets

---

computed_by_test.go
parser.go
tree.go
worksheets.go
worksheets_test.go

And improving other error messages in the process.

Prevent index 0 from being used to define fields

---

computed_by_test.go
constrained_by_test.go
parser.go
tree.go
worksheets.go
worksheets_test.go

@pascallouisperez I took a shot at #47, let me know how it's looking so far

first draft of adding constraints to fields

---

values.go
values_test.go

Fix String() bug for non-int negative numbers

---

parser_test.go
values.go
values_test.go

Do numerical comparison when testing number equality

---

expressions.go
parser.go
parser_test.go
runtime_test.go
testutil_test.go
tree.go
values.go

Other functions (e.g. filter) should be easy to add.
Closes #68 
@workmajj Want to add `first_of` after, and `filter`?

Adding support for len and sum

---

.circleci/config.yml

Added more go versions to run in parallel for building.

Add more go versions to build process fixes #82

---

expressions.go
expressions_test.go
runtime_test.go

Pretty simple, except that we need to defer execution of the if-branch and else-branch values to when they are needed, rather than compute them on entry to the function. Introducing `fnArgs` to handle this compute-on-first-get behavior.

Adding if function

---

clone.go
clone_test.go
computed_by_test.go
constrained_by_test.go
dbstore.go
dbstore_test.go
enums_test.go
expressions.go
expressions_test.go
marshaling_test.go
parser.go
parser_test.go
refs_test.go
runtime_test.go
values.go
values_test.go
worksheets.go
worksheets_test.go

In short, before this change, you had to write
return if(
who == "pratik",    "yes", if(
who == "jane",      "no", if(
who == "the_devil", "42!",
undefined
)))
and after this change, it simplifies to
return first_of(
if(who == "pratik",    "yes" ),
if(who == "jane",      "no"  ),
if(who == "the_devil", "42!" ),
)
Each commit is meant to be reviewed individually.

Extending if, and adding first_of

---

examples/tic_tac_toe.ws
marshaling.go
marshaling_test.go
testutil_test.go
values.go

this is the last part based on the other 2 prs, it adds support for graphs.

structscan worksheets/slices

---

README.md
bench_test.go
schema.sql
testutil_test.go

Benchmarking load, and updates to the schema to include indexes.

---

wstesting/wstesting.go
wstesting/wstesting_test.go

… which recently moved the AST into a separate package (cucumber-messages-go)

Fixing our use of gherkin-go

---

wstesting/wstesting.go
wstesting/wstesting_test.go

github.com/cucumber/cucumber-messages-go changed where its files are to dir v2

cucumber messages v2

---

.circleci/config.yml

https://app.clubhouse.io/homelight/story/14621
[ch14621]

update branch ref master->main

---

dbstore.go
dbstore_test.go

Added a test, watched it fail, implemented the fix.

add test & fix empty slice element bug
